use crate::Error;

pub const MAX_CAPABILITY_ID: usize = 32;

/// Stable, fixed-size identifier for a system capability.
///
/// IDs are UTF-8 strings such as `sys:log` or `sys:store`. The fixed array
/// layout keeps the type `no_std` and allocation-free.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub struct CapabilityId {
    bytes: [u8; MAX_CAPABILITY_ID],
    len: u8,
}

impl CapabilityId {
    pub const fn new(bytes: &[u8]) -> Option<Self> {
        if bytes.is_empty() || bytes.len() > MAX_CAPABILITY_ID {
            return None;
        }
        let mut storage = [0u8; MAX_CAPABILITY_ID];
        let mut index = 0;
        while index < bytes.len() {
            storage[index] = bytes[index];
            index += 1;
        }
        Some(Self {
            bytes: storage,
            len: bytes.len() as u8,
        })
    }

    pub const fn from_str(value: &str) -> Option<Self> {
        Self::new(value.as_bytes())
    }

    pub fn as_bytes(&self) -> &[u8] {
        &self.bytes[..self.len as usize]
    }

    pub fn as_str(&self) -> Option<&str> {
        core::str::from_utf8(self.as_bytes()).ok()
    }
}

/// Capability interface version. Only major and minor are tracked because
/// capabilities are ABI boundaries: patch-level changes must not alter the
/// interface.
#[derive(Clone, Copy, Debug, Eq, PartialEq, PartialOrd, Ord)]
pub struct CapabilityVersion {
    pub major: u16,
    pub minor: u16,
}

impl CapabilityVersion {
    pub const fn new(major: u16, minor: u16) -> Self {
        Self { major, minor }
    }
}

/// A capability required by a module package.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CapabilityRequirement {
    pub id: CapabilityId,
    pub min_version: CapabilityVersion,
}

impl CapabilityRequirement {
    /// Encode a requirement into `output`. Returns bytes written.
    pub fn encode(&self, output: &mut [u8]) -> Result<usize, Error> {
        let id_bytes = self.id.as_bytes();
        let total = 1 + id_bytes.len() + 4;
        if output.len() < total {
            return Err(Error::BufferTooSmall);
        }
        output[0] = id_bytes.len() as u8;
        output[1..1 + id_bytes.len()].copy_from_slice(id_bytes);
        let mut offset = 1 + id_bytes.len();
        output[offset..offset + 2].copy_from_slice(&self.min_version.major.to_le_bytes());
        offset += 2;
        output[offset..offset + 2].copy_from_slice(&self.min_version.minor.to_le_bytes());
        Ok(total)
    }

    /// Decode a requirement from `input`. Returns `(requirement, bytes_consumed)`.
    pub fn decode(input: &[u8]) -> Result<(Self, usize), Error> {
        if input.is_empty() {
            return Err(Error::InvalidPacket);
        }
        let id_len = input[0] as usize;
        if id_len == 0 || id_len > MAX_CAPABILITY_ID || input.len() < 1 + id_len + 4 {
            return Err(Error::InvalidPacket);
        }
        let id = CapabilityId::new(&input[1..1 + id_len]).ok_or(Error::InvalidPacket)?;
        let mut offset = 1 + id_len;
        let major = u16::from_le_bytes([input[offset], input[offset + 1]]);
        offset += 2;
        let minor = u16::from_le_bytes([input[offset], input[offset + 1]]);
        offset += 2;
        Ok((
            Self {
                id,
                min_version: CapabilityVersion::new(major, minor),
            },
            offset,
        ))
    }
}

/// A system-provided, versioned capability.
///
/// Capabilities differ from regular Vibe modules:
/// - They are provided by the system/ firmware/ host, not generated by AI.
/// - They have a stable ID and version that modules can declare as a dependency.
/// - They are always resident and are not loaded/unloaded like modules.
pub trait Capability {
    fn id(&self) -> CapabilityId;
    fn version(&self) -> CapabilityVersion;
    fn invoke(&mut self, input: &[u8], output: &mut [u8]) -> Result<usize, Error>;
}

/// Registry of installed capabilities. Implemented by each platform.
pub trait CapabilityRegistry {
    fn invoke(&mut self, id: CapabilityId, input: &[u8], output: &mut [u8])
    -> Result<usize, Error>;
    fn has(&self, id: CapabilityId, min_version: CapabilityVersion) -> bool;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Error;

    struct DummyCapability {
        value: u8,
    }

    impl Capability for DummyCapability {
        fn id(&self) -> CapabilityId {
            CapabilityId::from_str("sys:dummy").unwrap()
        }

        fn version(&self) -> CapabilityVersion {
            CapabilityVersion::new(1, 2)
        }

        fn invoke(&mut self, input: &[u8], output: &mut [u8]) -> Result<usize, Error> {
            if output.is_empty() {
                return Err(Error::BufferTooSmall);
            }
            output[0] = self.value;
            if let Some(byte) = input.first() {
                self.value = self.value.wrapping_add(*byte);
            }
            Ok(1)
        }
    }

    struct TestRegistry {
        dummy: DummyCapability,
    }

    impl CapabilityRegistry for TestRegistry {
        fn invoke(
            &mut self,
            id: CapabilityId,
            input: &[u8],
            output: &mut [u8],
        ) -> Result<usize, Error> {
            if id != self.dummy.id() {
                return Err(Error::CapabilityNotFound);
            }
            self.dummy.invoke(input, output)
        }

        fn has(&self, id: CapabilityId, min_version: CapabilityVersion) -> bool {
            id == self.dummy.id() && self.dummy.version() >= min_version
        }
    }

    #[test]
    fn round_trip_capability_id() {
        let id = CapabilityId::from_str("sys:log").unwrap();
        assert_eq!(id.as_bytes(), b"sys:log");
        assert_eq!(id.as_str(), Some("sys:log"));
    }

    #[test]
    fn rejects_empty_or_long_capability_id() {
        assert!(CapabilityId::new(b"").is_none());
        assert!(CapabilityId::new(&[0u8; 33]).is_none());
    }

    #[test]
    fn encodes_and_decodes_requirement() {
        let req = CapabilityRequirement {
            id: CapabilityId::from_str("sys:store").unwrap(),
            min_version: CapabilityVersion::new(2, 1),
        };
        let mut buffer = [0u8; 64];
        let len = req.encode(&mut buffer).unwrap();
        let (decoded, consumed) = CapabilityRequirement::decode(&buffer[..len]).unwrap();
        assert_eq!(consumed, len);
        assert_eq!(decoded.id.as_bytes(), b"sys:store");
        assert_eq!(decoded.min_version, CapabilityVersion::new(2, 1));
    }

    #[test]
    fn registry_invokes_and_tracks_version() {
        let mut registry = TestRegistry {
            dummy: DummyCapability { value: 10 },
        };
        let id = CapabilityId::from_str("sys:dummy").unwrap();

        assert!(registry.has(id, CapabilityVersion::new(1, 2)));
        assert!(!registry.has(id, CapabilityVersion::new(1, 3)));

        let mut output = [0u8; 4];
        let len = registry.invoke(id, b"\x05", &mut output).unwrap();
        assert_eq!(len, 1);
        assert_eq!(output[0], 10);

        let len = registry.invoke(id, b"\x03", &mut output).unwrap();
        assert_eq!(len, 1);
        assert_eq!(output[0], 15);
    }
}
